services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: travel_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8040:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin